-- Gambitron frontend-only persistence schema.
-- Run this in Supabase SQL Editor, then set VITE_SUPABASE_URL and
-- VITE_SUPABASE_ANON_KEY in the frontend deployment environment.

create table if not exists public.games (
  id uuid primary key,
  created_at timestamptz not null default now(),
  ended_at timestamptz,
  time_control_ms integer not null,
  result text,
  termination text,
  player_color text not null check (player_color in ('white', 'black')),
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.game_moves (
  id bigint generated by default as identity primary key,
  game_id uuid not null references public.games(id) on delete cascade,
  ply integer not null,
  fen text not null,
  san text not null,
  from_square text,
  to_square text,
  captured text,
  color text check (color in ('w', 'b')),
  created_at timestamptz not null default now(),
  unique (game_id, ply)
);

create index if not exists idx_games_created_at on public.games(created_at desc);
create index if not exists idx_game_moves_game_id_ply on public.game_moves(game_id, ply);

alter table public.games enable row level security;
alter table public.game_moves enable row level security;

drop policy if exists "Public read games" on public.games;
create policy "Public read games"
  on public.games for select
  using (true);

drop policy if exists "Public insert games" on public.games;
create policy "Public insert games"
  on public.games for insert
  with check (true);

drop policy if exists "Public read game moves" on public.game_moves;
create policy "Public read game moves"
  on public.game_moves for select
  using (true);

drop policy if exists "Public insert game moves" on public.game_moves;
create policy "Public insert game moves"
  on public.game_moves for insert
  with check (true);
